AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyApiFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdas/app.lambda_handler
      Runtime: python3.11
      Events:
        YearsApi:
          Type: Api
          Properties:
            Path: /years
            Method: GET
        MoviesByIdApi:
          Type: Api
          Properties:
            Path: /movies/{id}
            Method: GET
        MoviesByYearApi:
          Type: Api
          Properties:
            Path: /movies/year/{year}
            Method: GET

Outputs:
  YearsApiEndpoint:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/years'
  MoviesByIdApiEndpoint:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/movies/{id}'
  MoviesByYearApiEndpoint:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/movies/year/{year}'
